security:
    password_hashers:
        App\Entity\Gestionnaire: plaintext
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext
    providers:
        gestionnaire_provider:
            entity:
                class: App\Entity\Gestionnaire
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: gestionnaire_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_dashboard
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/gestionnaire, roles: ROLE_GESTIONNAIRE }
        - { path: ^/login, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_GESTIONNAIRE: [ROLE_USER]