# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Chargement automatique de toutes les classes dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    # --- ALIAS POUR LES REPOSITORIES ---
    # Plus besoin de factory ou d'arguments, l'autowire s'en occupe
    App\Repository\Interface\CommandeRepositoryInterface: '@App\Repository\CommandeRepository'
    App\Repository\Interface\GestionnaireRepositoryInterface: '@App\Repository\GestionnaireRepository'
    App\Repository\Interface\ZoneRepositoryInterface: '@App\Repository\ZoneRepository'
    App\Repository\Interface\StatistiqueRepositoryInterface: '@App\Repository\StatistiqueRepository'

    # --- ALIAS POUR LES SERVICES ---
    # Symfony liera automatiquement l'interface à la classe
    App\Service\Interface\CommandeServiceInterface: '@App\Service\CommandeService'
    App\Service\Interface\StatistiqueServiceInterface: '@App\Service\StatistiqueService'
    App\Service\Interface\LivraisonServiceInterface: '@App\Service\LivraisonService'
    App\Service\Interface\AuthenticationServiceInterface: '@App\Service\AuthenticationService'
    App\Repository\MenuRepositoryInterface: '@App\Repository\MenuRepository'